### ISSUE TITLE
Mistake Bug

### ISSUE THREAD

**Issue by danya201272** [educatalan02/RichAnnouncer#2]
What is space between messages
![image](https://user-images.githubusercontent.com/36302863/69452551-008f1a80-0d73-11ea-99b0-b53e16ad7a21.png)
![image](https://user-images.githubusercontent.com/36302863/69452583-100e6380-0d73-11ea-85b6-d5fdea863e84.png)
![image](https://user-images.githubusercontent.com/36302863/69452608-22889d00-0d73-11ea-934f-258c5576dbd5.png)

**Comment by educatalan02** [comment]
You're using Wrong Size that isn't recommended and too much text for one Announcement which is not supported by Unturned itselfs.
