### ISSUE TITLE
Mistake in load

### ISSUE THREAD

**Issue by danya201272** [educatalan02/RichAnnouncer#3]
RichAnnouncer >> RichAnnouncer loaded correctly by educatalan02#1236
[RichAnnouncer] Discord Support: discord.gg/Q89FmUk
Fallback handler could not load library D:/Steam/steamapps/common/U3DS/Unturned_Data/Mono/data-0000022528FEE160.dll

**Comment by educatalan02** [comment]
This error isn't related to my plugin.
